### ISSUE TITLE
As a user I need the ability to add an official image/logo for a skill

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#141]
In the Add Skill Modal at a form for adding a photo.  

TODO: Discuss the photo size limitations
TODO: Discuss how to pass the image in GET/POST calls
TODO: Discuss how to save the image to Cassandra

**Comment by Hopding** [comment]
I've done a bit of research and this is what I've come up with:

* **Saving image in Cassandra:** Cassandra is not designed to store files. It is
only supposed to store bytes, essentially. So the image will have to be
converted to an array of bytes, and then stored in a [`Blob` column](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/blob_r.html)
(`Blob`s are just arbitrary byte sequences).
* **Photo size limitations:** Since we will need to store the photo in a `Blob`
column, it would be easiest if we avoided exceeding the [size limit](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/refLimits.html)
for a single `Blob` cell: 1 MB recommended. To give you an idea of images that
would fit in this size constraint, my [GitHub profile pic](https://avatars3.githubusercontent.com/u/10351828?v=3&s=460)
occupies about 20KB on my disk. There are [1000 KB in a MB](https://www.google.com/search?q=kb+in+a+mb&ie=utf-8&oe=utf-8),
so that seems to be ample space for our purposes.
* **How to pass image in HTTP requests:** HTTP is a text-based protocol. It
looks like the best way to transmit the image would be to convert it into a
sequence of bytes, and store that sequence in a request body. The byte sequence
can be reconstructed as an image on the UI side. This would also work well with the backend,
since it would be sending & receiving images as byte sequences, and wouldn't 
need to do the conversion itself.

Relevant Links:

* https://docs.datastax.com/en/cql/3.1/cql/cql_reference/refLimits.html
* http://stackoverflow.com/questions/17207868/how-to-read-file-from-cassandra-and-write-file-to-cassandra
* https://docs.datastax.com/en/cql/3.1/cql/cql_reference/blob_r.html
* https://docs.datastax.com/en/cql/3.1/cql/cql_reference/cql_data_types_c.html?hl=types
* http://stackoverflow.com/questions/23090553/when-to-use-blobs-in-a-cassandra-and-cql-table-and-what-are-blobs-exactly
* https://www.google.com/search?q=kb+in+a+mb&ie=utf-8&oe=utf-8

**Comment by dane-johnson** [comment]
I know I have always been taught *not* to save images to a database. Often I have heard that it is best to have a separate service to host images, and store urls in the database.

**Comment by Hopding** [comment]
@dane-johnson Any particular reason for that? Was that a best-practices recommendation, or just a way to avoid excessive complication for a particular project?

**Comment by dane-johnson** [comment]
I believe the explanation was that relational databases are not designed for raw binary data.

**Comment by Hopding** [comment]
Did some googling, and it looks like if you are going to be storing a lot of photos for a lot of different purposes, then you should store the images in the filesystem, and keep their filepaths as database entries. But, I don't know if this applies to our situation. We probably won't be storing images for any other purpose, so it doesn't seem worth it to add an additional layer of complexity. 

The images we are working with should also be small enough to fit in a single `Blob` cell, so it _shouldn't_ be overly complicated to just leverage the database for this (would be a different story if we had to implement a system to split up an image's data across multiple cells).

**Comment by Hopding** [comment]
Would we just want to add a `Blob` field to the `skills` table and cause the image to be transmitted on all GETs, and be optional in POSTs/PUTs?

**Comment by thebho** [comment]
Yeah, that is what I want to try
