### ISSUE TITLE
Refactor skillreview endpoints

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/skilldirectory#151]
The Cassandra database has been refactored to allow for more complex queries concerning the skill reviews. Refactor the queries being made to account for this. See [this PR](https://github.com/maryvilledev/skilldirectoryinfra/pull/11).

**Comment by dane-johnson** [comment]
GET requests should be refactored to select an optimal for the type of query (by_skill for queries based on the skill, by_year for queries based on time).
POST requests should add the data to both tables.
PUT and DELETE requests need to require the skill_id and timestamp in the request body

**Comment by Hopding** [comment]
@dane-johnson a couple of points:
* It seems rather awkward to require PUT and DELETE requests to contain the `skill_id` and `timestamp` of a review. Why is the necessary? If the API needs this data to do its thing, then it seems to me that it should only require the `skill_review_id`, and then perform additional queries internally to get whatever other data it needs, but not require the client to get the data for it.
* I believe that, currently, it is only possible to do a "bulk GET" or an "individual GET" on `/skillreviews`, and I don't think query filters have any effect. So, unless we add or modify how the API, then there isn't currently any use for the `by_year` table.

     ~Perhaps we should change "bulk GET" responses to only contain the 5 or 10 most recent reviews, or process query filters in request URLs?~ (see #147)

**Comment by dane-johnson** [comment]
Cassandra is a different beast than we originally thought she was. The best way to do a delete is really to know exactly which object you'd need to pop, and call delete on it. Within the domain of the project, that would really always be the case anyhow. If we need bulk PUT/DELETE capabilities, we need to research alternatives to Cassandra; however I do not think that is necessary.

**Comment by Hopding** [comment]
Since we are using two different tables to store skill reviews, how are we going to be able to allow a client to delete a skill from both tables? Of course, they would only make a single DELETE request, but what would the request contain? Formerly, it was possible to uniquely identify a skill review within the single table via its `uuid`, but this no longer works if we are using multiple tables to store the reviews.

It doesn't seem reasonable to require a client to specify the `skill_id` and `timestamp` fields:

1. It just seems awkward.
2. It is conceivable that two individuals would post a review at the same time, on the same skill. This is highly unlikely in a project the scope of ours, but if it was a bigger system, I think it would be a much greater concern.

I guess I'm assuming here that we aren't requiring identical UUIDs for skill review records across the two tables. If we are, then this isn't really a problem. If we aren't, perhaps we should?

**Comment by dane-johnson** [comment]
The fact is the timestamp and the skill_id are parts of the primary key and are therefore necessary for deletion. I don't think it is unreasonable to require that much information to perform a delete, since it should be a rare occurrence and the client should know **exactly** which review she would like to delete.

As for timestamp collisions, I think it is unlikely that two reviews be posted at the exact same time since there is precision down to a millisecond, but if this is a concern, we could look into using `timeuuid`s, (<http://docs.datastax.com/en/archived/cql/3.0/cql/cql_reference/cql_data_types_c.html>) which guarantee no collision

**Comment by Hopding** [comment]
I agree that it is unlikely for two reviews to be posted at the same time. It certainly isn't something that we _have_ to worry about actually happening in _this_ project. I'm just pointing out that it may not be a good best-practice (though, I don't have enough experience in database-design to know for sure either way).

I am not sure that just because a column is part of a table's primary key that we should require a client to specify it in DELETE requests. There are a number of other tables that have composite primary keys, but the API only requires clients to specify `uuid`s in DELETE requests. The API then uses that `uuid` to perform a lookup on the other required fields before performing the delete query. (It is possible that this is isn't an ideal approach? I'm not sure. But it certainly keeps things consistent across DELETE requests, and is easier for the client, I think).

Of course, this approach isn't possible if we don't replicate `uuid`s across the two review tables. I don't see why this would be poor design. If it is, then we could add another column to serve the same purpose?

**Comment by dane-johnson** [comment]
The problem here is we are still thinking about Cassandra in a relational mindset. Deletes can require more excise from the client because they should be infrequent. Querying the database for uuids is sub-optimal because it eliminates the benefits that we have gained by using Cassandra. If we know the primary key, we can find the data immediately, whereas if we query, we hop from node to node in search of it, and at that point we may have just as well used a relational database. These types of queries will slow with scale. We should move to build tables that are query-based, and not burden the database with these kinds of large-scope queries.

**Comment by Hopding** [comment]
That seems reasonable. But, if we are going to require a JSON body for `/skillreview` DELETEs, then I think we should also update the other endpoints to operate in like fashion? 

Right now, DELETE request URLs are structured as `/endpoints/ID`, with no body. Perhaps we should change this so that the `ID` component of the URL is not required? This is abnormal for a REST API, but I think we should keep our approach to DELETEs consistent across endpoints.

But, perhaps this isn't something to be concerned about since we'll be shelfing this project in a week.

**Comment by dane-johnson** [comment]
[This type of generic query](https://github.com/maryvilledev/skilldirectory/blob/master/data/cassandra.go#L110-L118) does not vibe with Cassandra the way it would with a relational database. We need to build simple queries for each table, rather than complex queries with many options that would work on each.

**Comment by dane-johnson** [comment]
See <http://docs.datastax.com/en/cql/3.1/cql/ddl/dataModelingApproach.html>

**Comment by dane-johnson** [comment]
I think since there is such a focus on the React component, we should perhaps create temporary sub-optimal functions in the API layer that provide a façade to clients, but we should be sure to mark them as such, so when the project is revived they can be replaced with proper Cassandra-friendly code.

**Comment by thebho** [comment]
I think optional ID on deletes is fine.  
If you get a DELETE with an ID and no object, throw an error.
If you get a DELETE with an ID that doesn't match the object ID, throw an error.
If you get a DELETE with an object and no ID, remove that review.  
If you get a DELETE with an ID the DOES match the object, remove that review

**Comment by thebho** [comment]
As long as the documentation states the rules, it's up to us to determine the validation and requirements
