### ISSUE TITLE
Skills need to have a the ability to save/read links to webpages, blogs, and tutorials

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#5]
When performing a get on a `Skill`, this is what I'm hoping to receive.
For example:
```
Skill{
  Name: "Java"
  Id: id_string
  Type: "compiled"
  Webpage: Link {Name: "Java Website", Url: "https://www.java.com/en/"}
  Blogs: []Link{Link{Name:"Java", Url: "http://www.javaworld.com/blog/java-101/"}}
  Tutorials: []Link{}
}
```

The Link type would be something like this.  I'm anticipating there will need to be a separate query to inject the links into a skill object
```
Link{
  Name string
  Url string
  Skill_Id string
  LinkType string //blog, tutorial, webpage
}
```

**Comment by Hopding** [comment]
Could you explain this is a bit more detail? It's not clear to me what specifically you are looking for here.

**Comment by thebho** [comment]
Yeah, I'll flesh this out a little more this afternoon.

**Comment by Hopding** [comment]
You said

> I'm anticipating there will need to be a separate query to inject the links into a skill object

Perhaps it would be better to address this specific issue by simply adding fields to `Skill` objects so that they can store the appropriate links when POSTing a new skill, and return the links on GET requests.

A new request could then be opened for updating pre-existing`Skill`s via PUT requests.
